# Generated by Django 2.0.2 on 2018-03-02 22:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reagents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Matter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('owner', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='Reagent',
        ),
        migrations.CreateModel(
            name='Biologic',
            fields=[
                ('matter_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='reagents.Matter')),
                ('sequence', models.CharField(max_length=255)),
                ('form', models.CharField(choices=[('p', 'plasmid'), ('l', 'genomic'), ('r', 'recombinant')], max_length=1)),
                ('shape', models.CharField(choices=[('c', 'circular'), ('l', 'linear')], max_length=1)),
                ('material', models.CharField(choices=[('dD', 'dsDNA'), ('sD', 'ssDNA'), ('dR', 'dsRNA'), ('sR', 'ssRNA'), ('pp', 'protein')], max_length=2)),
            ],
            bases=('reagents.matter',),
        ),
        migrations.CreateModel(
            name='Liquid',
            fields=[
                ('matter_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='reagents.Matter')),
            ],
            bases=('reagents.matter',),
        ),
        migrations.CreateModel(
            name='Solid',
            fields=[
                ('matter_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='reagents.Matter')),
                ('mw', models.CharField(max_length=20)),
            ],
            bases=('reagents.matter',),
        ),
        migrations.CreateModel(
            name='Solution',
            fields=[
                ('matter_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='reagents.Matter')),
            ],
            bases=('reagents.matter',),
        ),
    ]
