# Generated by Django 2.0.2 on 2018-03-05 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reagents', '0002_auto_20180302_2229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biologic',
            name='form',
            field=models.CharField(choices=[('  plasmid  ', 'plasmid'), ('  genomic  ', 'genomic'), ('recombinant', 'recombinant')], max_length=11),
        ),
        migrations.AlterField(
            model_name='biologic',
            name='material',
            field=models.CharField(choices=[(' dsDNA ', 'dsDNA'), (' ssDNA ', 'ssDNA'), (' dsRNA ', 'dsRNA'), (' ssRNA ', 'ssRNA'), ('protein', 'protein')], max_length=7),
        ),
        migrations.AlterField(
            model_name='biologic',
            name='sequence',
            field=models.TextField(max_length=10000),
        ),
        migrations.AlterField(
            model_name='biologic',
            name='shape',
            field=models.CharField(choices=[('circular', 'circular'), (' linear ', 'linear')], max_length=8),
        ),
        migrations.AlterField(
            model_name='matter',
            name='owner',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
