# Generated by Django 2.0.2 on 2018-03-06 00:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reagents', '0004_auto_20180306_0000'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contains',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volume', models.CharField(max_length=16)),
                ('reagent', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='reagents.Liquid')),
            ],
        ),
        migrations.RemoveField(
            model_name='solution',
            name='biologics',
        ),
        migrations.RemoveField(
            model_name='solution',
            name='solids',
        ),
        migrations.RemoveField(
            model_name='solution',
            name='solutions',
        ),
        migrations.RemoveField(
            model_name='solution',
            name='liquids',
        ),
        migrations.AddField(
            model_name='contains',
            name='solution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='reagents.Solution'),
        ),
        migrations.AddField(
            model_name='solution',
            name='liquids',
            field=models.ManyToManyField(through='reagents.Contains', to='reagents.Liquid'),
        ),
    ]
