# Generated by Django 2.0.2 on 2018-03-06 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reagents', '0005_auto_20180306_0054'),
    ]

    operations = [
        migrations.CreateModel(
            name='BiologicContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mass', models.CharField(blank=True, max_length=16)),
                ('moles', models.CharField(blank=True, max_length=16)),
                ('reagent', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='reagents.Biologic')),
            ],
        ),
        migrations.CreateModel(
            name='LiquidContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volume', models.CharField(max_length=16)),
                ('reagent', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='reagents.Liquid')),
            ],
        ),
        migrations.CreateModel(
            name='SolidContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mass', models.CharField(blank=True, max_length=16)),
                ('moles', models.CharField(blank=True, max_length=16)),
                ('reagent', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='reagents.Solid')),
            ],
        ),
        migrations.RemoveField(
            model_name='contains',
            name='reagent',
        ),
        migrations.RemoveField(
            model_name='contains',
            name='solution',
        ),
        migrations.AlterField(
            model_name='solution',
            name='liquids',
            field=models.ManyToManyField(through='reagents.LiquidContent', to='reagents.Liquid'),
        ),
        migrations.DeleteModel(
            name='Contains',
        ),
        migrations.AddField(
            model_name='solidcontent',
            name='solution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='reagents.Solution'),
        ),
        migrations.AddField(
            model_name='liquidcontent',
            name='solution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='reagents.Solution'),
        ),
        migrations.AddField(
            model_name='biologiccontent',
            name='solution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='reagents.Solution'),
        ),
        migrations.AddField(
            model_name='solution',
            name='biologics',
            field=models.ManyToManyField(through='reagents.BiologicContent', to='reagents.Biologic'),
        ),
        migrations.AddField(
            model_name='solution',
            name='solids',
            field=models.ManyToManyField(through='reagents.SolidContent', to='reagents.Solid'),
        ),
    ]
