# Generated by Django 2.0.2 on 2018-03-22 21:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reagents', '0009_auto_20180307_1801'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cell',
            fields=[
                ('matter_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='reagents.Matter')),
                ('species', models.TextField(max_length=255)),
            ],
            bases=('reagents.matter',),
        ),
        migrations.CreateModel(
            name='CellBiologicContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cell', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reagents.Cell')),
                ('reagent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reagents.Biologic')),
            ],
        ),
        migrations.AddField(
            model_name='cell',
            name='biologics',
            field=models.ManyToManyField(through='reagents.CellBiologicContent', to='reagents.Biologic'),
        ),
    ]
