# Generated by Django 2.0.2 on 2018-03-22 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reagents', '0010_auto_20180322_2151'),
    ]

    operations = [
        migrations.AddField(
            model_name='cell',
            name='culture_environment',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='cell',
            name='doubling_time',
            field=models.FloatField(default=1),
        ),
        migrations.AddField(
            model_name='cell',
            name='doubling_time_units',
            field=models.CharField(choices=[('  s', 's'), ('min', 'min'), ('  h', 'h'), ('  d', 'y')], default='  h', max_length=3),
        ),
        migrations.AddField(
            model_name='cell',
            name='media_preference',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='cell',
            name='morphology',
            field=models.CharField(choices=[('fibro', 'fibroblastic'), ('epith', 'epithelial-like'), ('lymph', 'lymphoblast-like')], default='-----', max_length=5),
        ),
        migrations.AddField(
            model_name='cell',
            name='shaken',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='cell',
            name='species',
            field=models.TextField(default='E.Coli', max_length=255),
        ),
    ]
