# Generated by Django 2.0.2 on 2018-03-07 20:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protocols', '0002_auto_20180307_1953'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='protocol',
            name='name',
        ),
        migrations.RemoveField(
            model_name='step',
            name='date_range',
        ),
        migrations.RemoveField(
            model_name='step',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='step',
            name='protocol',
        ),
        migrations.RemoveField(
            model_name='step',
            name='start_date',
        ),
        migrations.AddField(
            model_name='protocol',
            name='date_range',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AddField(
            model_name='protocol',
            name='end_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='protocol',
            name='start_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='step',
            name='name',
            field=models.CharField(default='MyProtocol', max_length=255),
        ),
    ]
