# Generated by Django 2.0.2 on 2018-03-22 23:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reagents', '0011_auto_20180322_2320'),
        ('protocols', '0007_auto_20180322_2151'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddedCell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volume', models.FloatField(default=0)),
                ('volume_units', models.CharField(choices=[('ng/L', 'ng/L'), ('ug/L', 'ug/L'), ('mg/L', 'mg/L'), (' g/L', ' g/L'), (' nM ', ' nM '), (' uM ', ' uM '), (' mM ', ' mM '), ('  M ', '  M ')], default=' g/L', max_length=4)),
                ('reagent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reagents.Cell')),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='protocols.Step')),
            ],
        ),
        migrations.AddField(
            model_name='protocol',
            name='end_date',
            field=models.CharField(default='', max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='protocol',
            name='start_date',
            field=models.CharField(default='', max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='step',
            name='cells',
            field=models.ManyToManyField(through='protocols.AddedCell', to='reagents.Cell'),
        ),
    ]
