# Generated by Django 2.0.2 on 2018-03-23 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('protocols', '0008_auto_20180322_2320'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='protocol',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='protocol',
            name='start_date',
        ),
    ]
