# Generated by Django 2.0.2 on 2018-03-27 19:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('protocols', '0009_auto_20180323_1656'),
    ]

    operations = [
        migrations.CreateModel(
            name='Input',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_type', models.CharField(choices=[('Sample', 'Sample'), ('R.Enzy', 'Restriction Enzyme')], default='-----', max_length=30)),
                ('minimum_entries', models.IntegerField(default=1)),
                ('maximum_entries', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Output',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('output_type', models.CharField(choices=[('Sample', 'Sample'), ('R.Enzy', 'Restriction Enzyme')], default='-----', max_length=30)),
                ('minimum_entries', models.IntegerField(default=1)),
                ('maximum_entries', models.IntegerField(default=1)),
            ],
        ),
        migrations.RenameField(
            model_name='protocol',
            old_name='date_range',
            new_name='IO_template',
        ),
        migrations.AddField(
            model_name='step',
            name='defined_through_inputs',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='output',
            name='protocol',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='protocols.Protocol'),
        ),
        migrations.AddField(
            model_name='input',
            name='protocol',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='protocols.Protocol'),
        ),
    ]
