# Generated by Django 2.0.2 on 2018-03-07 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('protocols', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_range', models.CharField(max_length=15)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
        ),
        migrations.RemoveField(
            model_name='protocol',
            name='date_range',
        ),
        migrations.RemoveField(
            model_name='protocol',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='protocol',
            name='start_date',
        ),
        migrations.AddField(
            model_name='protocol',
            name='name',
            field=models.CharField(default='MyProtocol', max_length=255),
        ),
        migrations.AddField(
            model_name='step',
            name='protocol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='protocols.Protocol'),
        ),
    ]
