# Generated by Django 2.0.2 on 2018-03-07 20:22

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('protocols', '0003_auto_20180307_2004'),
    ]

    operations = [
        migrations.AddField(
            model_name='step',
            name='date_range',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AddField(
            model_name='step',
            name='end_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='step',
            name='protocol',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='protocols.Protocol'),
        ),
        migrations.AddField(
            model_name='step',
            name='start_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
