# Generated by Django 2.0.2 on 2018-03-14 23:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('protocols', '0004_auto_20180307_2022'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThermocycleStep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('Hold', 'Hold'), ('Goto', 'Goto')], default='Hold', max_length=4, null=True)),
                ('temperature', models.FloatField(default=23)),
                ('temperature_units', models.CharField(choices=[('C', 'C'), ('F', 'F')], default='C', max_length=4)),
                ('time', models.FloatField(default=1)),
                ('time_units', models.CharField(choices=[('  s', 's'), ('min', 'min'), ('  h', 'h'), ('  d', 'y')], default='min', max_length=3)),
            ],
        ),
        migrations.RemoveField(
            model_name='step',
            name='date_range',
        ),
        migrations.RemoveField(
            model_name='step',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='step',
            name='start_date',
        ),
        migrations.AddField(
            model_name='step',
            name='postamble',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='step',
            name='preamble',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='step',
            name='reagents',
            field=models.CharField(default='', max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='step',
            name='speed',
            field=models.FloatField(default=8000),
        ),
        migrations.AddField(
            model_name='step',
            name='speed_units',
            field=models.CharField(choices=[('  g', '  g'), ('rpm', 'rpm')], default='  g', max_length=3),
        ),
        migrations.AddField(
            model_name='step',
            name='temperature',
            field=models.FloatField(default=23),
        ),
        migrations.AddField(
            model_name='step',
            name='temperature_units',
            field=models.CharField(choices=[('C', 'C'), ('F', 'F')], default='C', max_length=4),
        ),
        migrations.AddField(
            model_name='step',
            name='time',
            field=models.FloatField(default=1),
        ),
        migrations.AddField(
            model_name='step',
            name='time_units',
            field=models.CharField(choices=[('  s', 's'), ('min', 'min'), ('  h', 'h'), ('  d', 'y')], default='min', max_length=3),
        ),
        migrations.AlterField(
            model_name='protocol',
            name='date_range',
            field=models.CharField(default='', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='step',
            name='name',
            field=models.CharField(choices=[('-----', '-----'), ('Mix', 'Mix'), ('Incubate', 'Incubate'), ('Centrifuge', 'Centrifuge'), ('Decant', 'Decant'), ('Thermocycle', 'Thermocycle'), ('Resuspend', 'Resuspend'), ('Transfer', 'Transfer'), ('Operate', 'Operate')], default='-----', max_length=255),
        ),
        migrations.AddField(
            model_name='thermocyclestep',
            name='step',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='protocols.Step'),
        ),
    ]
