# Generated by Django 2.0.2 on 2018-03-15 00:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('protocols', '0005_auto_20180314_2334'),
    ]

    operations = [
        migrations.RenameField(
            model_name='thermocyclestep',
            old_name='temperature',
            new_name='stage_temp',
        ),
        migrations.RenameField(
            model_name='thermocyclestep',
            old_name='temperature_units',
            new_name='stage_temp_units',
        ),
        migrations.RenameField(
            model_name='thermocyclestep',
            old_name='time',
            new_name='stage_time',
        ),
        migrations.RenameField(
            model_name='thermocyclestep',
            old_name='time_units',
            new_name='stage_time_units',
        ),
        migrations.RenameField(
            model_name='thermocyclestep',
            old_name='state',
            new_name='stage_type',
        ),
    ]
