# Generated by Django 2.0.2 on 2018-03-23 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('protocols', '0008_auto_20180322_2320'),
    ]

    operations = [
        migrations.CreateModel(
            name='InputProtocol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='OutputProtocol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='protocol',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='protocol',
            name='start_date',
        ),
        migrations.AddField(
            model_name='protocol',
            name='inputs',
            field=models.Field(default='', max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='protocol',
            name='outputs',
            field=models.CharField(default='', max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='outputprotocol',
            name='_output',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='protocols.Protocol'),
        ),
        migrations.AddField(
            model_name='inputprotocol',
            name='_input',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='protocols.Protocol'),
        ),
    ]
