# Generated by Django 2.0.2 on 2018-03-23 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('protocols', '0010_auto_20180323_1533'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inputprotocol',
            old_name='_input',
            new_name='protocol',
        ),
        migrations.RenameField(
            model_name='outputprotocol',
            old_name='_output',
            new_name='protocol',
        ),
    ]
