# Generated by Django 2.0.2 on 2018-03-23 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('protocols', '0011_auto_20180323_1534'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inputprotocol',
            name='protocol',
        ),
        migrations.RemoveField(
            model_name='outputprotocol',
            name='protocol',
        ),
        migrations.DeleteModel(
            name='InputProtocol',
        ),
        migrations.DeleteModel(
            name='OutputProtocol',
        ),
    ]
