# Generated by Django 2.0.2 on 2018-03-23 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protocols', '0012_auto_20180323_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='protocol',
            name='date_range',
            field=models.CharField(choices=[('            Custom', 'Custom'), ('          Miniprep', 'Miniprep'), ('          Zymoprep', 'Zymoprep'), ('         Transform', 'Transform'), ('   Electroporation', 'Electroporation'), ('      Transduction', 'Transduction'), ('             RTPCR', 'RT-PCR'), ('      Transciption', 'Transcription'), ('GelElectrophoresis', 'Gel Electrophoresis'), ('      GelExraction', 'Gel Extraction'), ('               PCR', 'PCR'), ('    GibsonAssembly', 'Gibson Assembly')], default='         Custom', max_length=15, null=True),
        ),
    ]
