# Generated by Django 2.0.2 on 2018-03-23 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('protocols', '0013_auto_20180323_1547'),
    ]

    operations = [
        migrations.CreateModel(
            name='InputProtocol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.CharField(max_length=255)),
                ('protocol', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='protocols.Protocol')),
            ],
        ),
        migrations.CreateModel(
            name='OutputProtocol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.CharField(max_length=255)),
                ('protocol', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='protocols.Protocol')),
            ],
        ),
    ]
